openapi: 3.0.0
info:
  title: Servicio de gestión de proveedores
  description: Servicio de gestión de proveedores (Hoteles, Transporte, etc...)
  version: 1.0
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licences/LICENSE-2.0.html"
    contact:
      name: "Byron Martínez, Edgar Javier Rivera, Rafael Ocampo, Fabian Burgos, Harry Sánchez"
      email: "jrafael.ocampo@javeriana.edu.co"
  servers:
    - url: 'https://localhost:8080/Cliente'
paths:
  
