openapi: 3.0.1
info:
  title: Service Order Manager
  description: ""
  termsOfService: ""
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
tags:
- name: Order Manager
  description: order manager
- name: user
  description: Operations about user
paths:
  /order/manager/register:
    put:
      tags:
      - order
      summary: Register a sales order
      operationId: registerOrder
      requestBody:
        description: Order object with all items that needs to be added to the database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: Success register order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        401:
          description: Unauthorized
          content: {}
      security:
      - touresbalon_auth:
        - write:order
      x-codegen-request-body-name: body
  /order/manager/{orderId}:
    get:
      tags:
      - get an order
      summary: Get a order by orderId
      operationId: queryOrderById
      parameters:
      - name: orderId
        in: path
        description: id of order to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullOrder'
        404:
          description: Order not found
          content: {}
      security:
      - touresbalon_auth:
        - read:order
  /order/manager/{custId}:
    get:
      tags:
      - get orders
      summary: Get a list of orders by custId
      operationId: queryOrdersByCustId
      parameters:
      - name: custId
        in: path
        description: id of customer to return a list of orders
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdersList'
        404:
          description: Orders not found
          content: {}
      security:
      - touresbalon_auth:
        - read:order
  /order/manager/status:
    put:
      tags:
      - order status
      summary: Update a sales order status
      operationId: updateOrder
      requestBody:
        description: Status object with the order id to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdate'
        required: true
      responses:
        200:
          description: Success register order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        401:
          description: Unauthorized
          content: {}
      security:
      - touresbalon_auth:
        - write:order
      x-codegen-request-body-name: body
  /order/manager/bookings:
    put:
      tags:
      - bookings
      summary: Update booking of the orders
      operationId: confirmBookingByOrder
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderBooking'
        required: true
      responses:
        200:
          description: Success update order
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        405:
          description: Invalid input
          content: {}
      security:
      - touresbalon_auth:
        - write:order
        - read:order
      x-codegen-request-body-name: body
components:
  schemas:
    Order:
      type: object
      properties:
        custId:
          type: string
          example: CC159753
        totalPrice:
          type: number
          format: double
          example: 1.852E+7
        comments:
          type: string
          example: Orden de compra para partidos de eliminatorias en Barranquilla
        items:
          type: array
          items:
            $ref: '#/components/schemas/Producto'
    StatusUpdate:
      type: object
      properties:
        custId:
          type: string
          example: CC159753
        ordId:
          type: string
          example: OVTB-001
        status:
          $ref: '#/components/schemas/Status'
    Status:
      type: object
      properties:
        status:
          type: string
          description: Order Status
          enum:
          - En Validación
          - En Reservación
          - Cerrada
          - Rechazada
          - Cancelada
    Producto:
      type: object
      properties:
        quantity:
          type: integer
          example: 1
        transportType:
          $ref: '#/components/schemas/Transporte'
        eventType:
          $ref: '#/components/schemas/Espectaculo'
        hostType:
          $ref: '#/components/schemas/Hospedaje'
    Transporte:
      type: object
      properties:
        provider:
          type: string
          example: AA00126
        departureDate:
          type: string
          example: 2020-09-12
        arriveDate:
          type: string
          example: 2020-09-14
        flyId:
          type: integer
          example: 123569
        price:
          type: number
          format: double
          example: 3694562.0
    Espectaculo:
      type: object
      properties:
        eventId:
          type: integer
          example: 956845
        price:
          type: number
          format: double
          example: 2875900.0
    Hospedaje:
      type: object
      properties:
        hotel:
          type: string
          example: Dann Carlton
        country:
          type: string
          example: Colombia
        city:
          type: string
          example: Barranquilla
        address:
          type: string
          example: Calle 123
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/Room'
        checkInDate:
          type: string
          example: 2020-09-12
        checkOutDate:
          type: string
          example: 2020-09-14
        price:
          type: number
          format: double
          example: 5946100.0
    Room:
      type: object
      properties:
        occupation:
          type: string
          example: double
    OrderBooking:
      type: object
      properties:
        custId:
          type: string
          example: CC159753
        orderId:
          type: string
          example: OVTB-001
        items:
          type: array
          items:
            $ref: '#/components/schemas/Booking'
    Booking:
      type: object
      properties:
        hotel:
          type: string
          example: DC-15648CR
        transport:
          type: string
          example: WD7845F
        event:
          type: string
          example: "152369"
    OrdersList:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/FullOrder'
    FullOrder:
      type: object
      properties:
        custId:
          type: string
          example: CC159753
        orderId:
          type: string
          example: OVTB-001
        orderDate:
          type: string
          example: 2020-08-12
        totalPrice:
          type: number
          format: double
          example: 1.852E+7
        comments:
          type: string
          example: Orden de compra para partidos de eliminatorias en Barranquilla
        items:
          type: array
          items:
            $ref: '#/components/schemas/Producto'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
        orderId:
          type: string
  securitySchemes:
    touresbalon_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://touresbalon.swagger.io/oauth/dialog
          scopes:
            write:order: register and modify order in the system
            read:order: Get the order
    api_key:
      type: apiKey
      name: api_key
      in: header
